version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html/
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/before_starting_cmd.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/after_installing_cmd.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/application_starting_cmd.sh
      timeout: 300
      runas: root

permissions:
  - object: /var/www/html/storage/**
    pattern: "-"
    owner: nginx
    group: nginx
    mode: 755
